### ISSUE TITLE
Use GH pages to serve this repo

### ISSUE THREAD

**Issue by stannlee** [Joannjuguna/portfolio_template#1]
Hi, I've seen your what you are doing here and I'm quite impressed
### However I have some recommendations

- Move this code to a repository named `joannguguna.github.io`. 

- Go tho the repo settings and enable GitHub pages. This will enable your portfolio to be served at [https://joannguguna.github.io](https://joannguguna.github.io)

_Happy coding_

**Comment by Joannjuguna** [comment]
Hey Stanley,

Thank you for your email.
I had initially hosted it on GitHub pages. I however, had not completed the
whole portfolio hence pulled it down from there.
Once I do I will push the latest changes and do that.

Kind regards,
Joan Nyambura Njuguna
